import { MODULE_KINDS, PARTNERSHIP_TYPES, PARTNERSHIP_TYPE_LABELS, PARTNER_TYPES, PARTNER_TYPE_LABELS, PROGRAMME_TYPES, PROGRAMME_TYPE_LABELS } from "@/lib/enums";
import { f, featuredAndOrder, governance, seo } from "../fields";
import type { EntityDef } from "../types";

const MODULE_KIND_LABELS: Record<string, string> = { CORE: "Core", SUBJECT: "Subject", SKILLS: "Skills", ENGLISH: "English" };

const str = (v: unknown) => (typeof v === "string" ? v : "");

export const programme: EntityDef = {
  key: "programmes",
  type: "Programme",
  delegate: "programme",
  label: "Programmes",
  labelSingular: "Programme",
  description: "NCUK and college programmes. Public detail pages are generated from these records.",
  titleField: "title",
  searchFields: ["title", "shortTitle", "code", "slug"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "code", label: "Code", kind: "mono" },
    { key: "type", label: "Type", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "reviewDate", label: "Review", kind: "date" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["title", "updatedAt", "sortOrder", "reviewDate"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  hasPublishAt: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.text("shortTitle", "Short title"),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the title." }),
    f.text("code", "Code", { maxLength: 20 }),
    f.select("type", "Programme type", PROGRAMME_TYPES, PROGRAMME_TYPE_LABELS),
    f.text("awardingBody", "Awarding body"),
    f.text("level", "Level"),
    f.textarea("summary", "Summary", { required: true, fullWidth: true, maxLength: 600 }),
    f.markdown("description", "Description", { nonNull: true, fullWidth: true }),
    f.textarea("whoFor", "Who it is for", { group: "details", fullWidth: true }),
    f.text("studyLocation", "Study location", { group: "details", nonNull: true }),
    f.text("durationLabel", "Duration label", { group: "details" }),
    f.number("durationMonths", "Duration (months)", { group: "details", integer: true, min: 1, max: 60 }),
    f.stringArray("intakesJson", "Intakes", { group: "details", hint: "One per line, e.g. September 2026." }),
    f.stringArray("subjectRoutesJson", "Subject routes", { group: "details", hint: "One per line." }),
    f.markdown("entryRequirements", "Entry requirements", { group: "details", fullWidth: true }),
    f.textarea("englishRequirement", "English requirement", { group: "details", fullWidth: true }),
    f.textarea("assessment", "Assessment", { group: "details", fullWidth: true }),
    f.text("qualification", "Qualification awarded", { group: "details" }),
    f.markdown("progression", "Progression", { group: "details", fullWidth: true }),
    f.markdown("whatNext", "What next", { group: "details", fullWidth: true }),
    f.textarea("applicationNotes", "Application notes", { group: "details", fullWidth: true }),
    f.media("heroMediaId", "Hero image", ["IMAGE"], { group: "details" }),
    ...featuredAndOrder,
    f.date("publishAt", "Publish at", { group: "details", hint: "Set a future date to schedule publication." }),
    ...governance({ verification: true, sourceNote: true, owner: true, effectiveDate: true, reviewDate: true }),
    ...seo(),
  ],
  children: [
    {
      key: "modules",
      label: "Modules",
      labelSingular: "Module",
      delegate: "programmeModule",
      parentField: "programmeId",
      titleField: "title",
      fields: [
        f.text("title", "Module title", { required: true }),
        f.select("kind", "Kind", MODULE_KINDS, MODULE_KIND_LABELS),
        f.number("credits", "Credits", { integer: true, min: 0, max: 200 }),
        f.textarea("description", "Description", { fullWidth: true }),
      ],
    },
  ],
  publicPaths: (r) => ["/", "/programmes", `/programmes/${str(r.slug)}`, "/pathways", "/compare", "/pathway-finder"],
};

export const pathway: EntityDef = {
  key: "pathways",
  type: "Pathway",
  delegate: "pathway",
  label: "Pathways",
  labelSingular: "Pathway",
  description: "Routes from Vientiane to a destination and university. Steps drive the timeline and the map.",
  titleField: "title",
  searchFields: ["title", "code", "slug", "subjectArea"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "code", label: "Code", kind: "mono" },
    { key: "subjectArea", label: "Subject" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "reviewDate", label: "Review", kind: "date" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["title", "updatedAt", "sortOrder", "reviewDate"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the title." }),
    f.text("code", "Route code", { maxLength: 20 }),
    f.textarea("summary", "Summary", { nonNull: true, fullWidth: true, maxLength: 600 }),
    f.text("startLocation", "Start location", { nonNull: true }),
    f.relation("programmeId", "Programme", "programme", "title"),
    f.text("subjectArea", "Subject area"),
    f.relation("destinationId", "Destination", "destination", "country"),
    f.relation("universityId", "University", "university", "name"),
    f.text("partnerName", "Partner name", { group: "details" }),
    f.text("qualification", "Final qualification", { group: "details" }),
    f.text("field", "Field of study", { group: "details" }),
    f.text("structureLabel", "Structure label", { group: "details", hint: "e.g. 1 + 3" }),
    f.text("totalDurationLabel", "Total duration", { group: "details" }),
    f.text("transferPoint", "Transfer point", { group: "details" }),
    f.markdown("progressionRequirements", "Progression requirements", { group: "details", fullWidth: true }),
    f.markdown("careerDirections", "Career directions", { group: "details", fullWidth: true }),
    f.textarea("applicationNotes", "Application notes", { group: "details", fullWidth: true }),
    ...featuredAndOrder,
    ...governance({ verification: true, sourceNote: true, owner: true, effectiveDate: true, reviewDate: true }),
  ],
  children: [
    {
      key: "steps",
      label: "Steps",
      labelSingular: "Step",
      delegate: "pathwayStep",
      parentField: "pathwayId",
      titleField: "label",
      fields: [
        f.text("label", "Label", { required: true }),
        f.text("location", "Location"),
        f.text("institution", "Institution"),
        f.text("duration", "Duration"),
        f.number("lat", "Latitude", { min: -90, max: 90 }),
        f.number("lng", "Longitude", { min: -180, max: 180 }),
        f.textarea("description", "Description", { fullWidth: true }),
      ],
    },
  ],
  publicPaths: (r) => ["/", "/pathways", `/pathways/${str(r.slug)}`, "/pathway-explorer", "/compare", "/pathway-finder"],
};

export const destination: EntityDef = {
  key: "destinations",
  type: "Destination",
  delegate: "destination",
  label: "Destinations",
  labelSingular: "Destination",
  description: "Countries students can progress to. Coordinates place the destination on the globe and map.",
  titleField: "country",
  searchFields: ["country", "isoCode", "slug", "region"],
  listColumns: [
    { key: "country", label: "Country" },
    { key: "isoCode", label: "ISO", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "reviewDate", label: "Review", kind: "date" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["country", "updatedAt", "sortOrder", "reviewDate"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("country", "Country", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the country." }),
    f.text("isoCode", "ISO code", { required: true, maxLength: 3, hint: "Two-letter code, e.g. GB." }),
    f.text("region", "Region"),
    f.number("lat", "Latitude", { required: true, min: -90, max: 90 }),
    f.number("lng", "Longitude", { required: true, min: -180, max: 180 }),
    f.textarea("summary", "Summary", { nonNull: true, fullWidth: true }),
    f.text("pathwayTypes", "Pathway types", { nonNull: true, group: "details", hint: "Short label shown on cards." }),
    f.textarea("durationNotes", "Duration notes", { group: "details", fullWidth: true }),
    f.markdown("requirements", "Requirements", { group: "details", fullWidth: true }),
    f.markdown("progressionNotes", "Progression notes", { group: "details", fullWidth: true }),
    f.url("officialLink", "Official link", { group: "details" }),
    f.media("heroMediaId", "Hero image", ["IMAGE"], { group: "details" }),
    ...featuredAndOrder,
    ...governance({ verification: true, sourceNote: true, reviewDate: true }),
  ],
  publicPaths: (r) => ["/", "/destinations", `/destinations/${str(r.slug)}`, "/pathway-explorer", "/universities"],
};

export const university: EntityDef = {
  key: "universities",
  type: "University",
  delegate: "university",
  label: "Universities",
  labelSingular: "University",
  description: "Progression universities. Partnership type is shown publicly; unverified entries carry a badge.",
  titleField: "name",
  searchFields: ["name", "city", "slug"],
  listColumns: [
    { key: "name", label: "Name" },
    { key: "city", label: "City" },
    { key: "partnershipType", label: "Partnership", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["name", "updatedAt", "sortOrder", "reviewDate"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("name", "Name", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the name." }),
    f.text("city", "City"),
    f.relation("destinationId", "Destination", "destination", "country"),
    f.url("website", "Website"),
    f.media("logoMediaId", "Logo", ["LOGO", "IMAGE"]),
    f.select("partnershipType", "Partnership type", PARTNERSHIP_TYPES, PARTNERSHIP_TYPE_LABELS),
    f.textarea("summary", "Summary", { nonNull: true, fullWidth: true }),
    f.textarea("programmesOffered", "Programmes offered", { group: "details", fullWidth: true }),
    f.markdown("progressionInfo", "Progression information", { group: "details", fullWidth: true }),
    f.text("transferPoint", "Transfer point", { group: "details" }),
    ...featuredAndOrder,
    ...governance({ verification: true, sourceNote: true, reviewDate: true }),
  ],
  publicPaths: (r) => ["/", "/universities", `/universities/${str(r.slug)}`, "/destinations"],
};

export const partner: EntityDef = {
  key: "partners",
  type: "Partner",
  delegate: "partner",
  label: "Partners",
  labelSingular: "Partner",
  description: "Awarding bodies, education and industry partners shown in logo walls and the about page.",
  titleField: "name",
  searchFields: ["name", "slug"],
  listColumns: [
    { key: "name", label: "Name" },
    { key: "type", label: "Type", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["name", "updatedAt", "sortOrder"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("name", "Name", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the name." }),
    f.select("type", "Partner type", PARTNER_TYPES, PARTNER_TYPE_LABELS),
    f.url("website", "Website"),
    f.media("logoMediaId", "Logo", ["LOGO", "IMAGE"]),
    f.markdown("description", "Description", { nonNull: true, fullWidth: true }),
    ...featuredAndOrder,
    ...governance({ verification: true, sourceNote: true }),
  ],
  publicPaths: () => ["/", "/about", "/why-st-hughs", "/for/partners"],
};
