import { DOCUMENT_CATEGORIES, DOCUMENT_CATEGORY_LABELS, FAQ_CATEGORIES, FAQ_CATEGORY_LABELS, NEWS_CATEGORIES, NEWS_CATEGORY_LABELS } from "@/lib/enums";
import { f, seo } from "../fields";
import type { EntityDef } from "../types";

const str = (v: unknown) => (typeof v === "string" ? v : "");
const VISIBILITY = ["PUBLIC", "INTERNAL"] as const;
const VISIBILITY_LABELS = { PUBLIC: "Public", INTERNAL: "Internal only" };
const TEMPLATES = ["STANDARD", "LANDING", "HOME"] as const;
const TEMPLATE_LABELS = { STANDARD: "Standard", LANDING: "Landing", HOME: "Home" };

export const page: EntityDef = {
  key: "pages",
  type: "Page",
  delegate: "page",
  label: "Pages",
  labelSingular: "Page",
  description: "Block-based pages. Save the page first, then assemble its blocks in the builder below the form.",
  titleField: "title",
  searchFields: ["title", "slug"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "slug", label: "Slug", kind: "mono" },
    { key: "template", label: "Template", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "publishAt", label: "Publish at", kind: "date" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["title", "slug", "updatedAt"],
  defaultSort: { field: "title", dir: "asc" },
  hasStatus: true,
  hasPublishAt: true,
  hasBlocks: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.slug("slug", "Slug", { hint: "URL path, e.g. privacy. Use 'home' for the homepage." }),
    f.select("template", "Template", TEMPLATES, TEMPLATE_LABELS),
    f.text("locale", "Locale", { nonNull: true, maxLength: 5, hint: "en for now." }),
    f.date("publishAt", "Publish at", { hint: "Set a future date to schedule publication." }),
    ...seo(),
    f.url("canonical", "Canonical URL", { group: "seo" }),
    f.text("ogTitle", "Open Graph title", { group: "seo" }),
    f.textarea("ogDescription", "Open Graph description", { group: "seo", maxLength: 300 }),
    f.media("ogImageId", "Open Graph image", ["IMAGE"], { group: "seo" }),
    f.boolean("noIndex", "Hide from search engines (noindex)", { group: "seo" }),
    f.json("structuredDataJson", "Structured data (JSON-LD)", { group: "seo", fullWidth: true, hint: "Optional JSON object merged into the page's JSON-LD." }),
  ],
  publicPaths: (r) => (str(r.slug) === "home" ? ["/"] : [`/${str(r.slug)}`]),
};

export const newsArticle: EntityDef = {
  key: "news",
  type: "NewsArticle",
  delegate: "newsArticle",
  label: "News",
  labelSingular: "Article",
  description: "News and insights. Scheduled publishing uses the 'Publish at' date.",
  titleField: "title",
  searchFields: ["title", "slug", "excerpt"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "category", label: "Category", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "publishAt", label: "Publish at", kind: "date" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["title", "updatedAt", "publishAt"],
  defaultSort: { field: "updatedAt", dir: "desc" },
  hasStatus: true,
  hasPublishAt: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the title." }),
    f.select("category", "Category", NEWS_CATEGORIES, NEWS_CATEGORY_LABELS),
    f.textarea("excerpt", "Excerpt", { nonNull: true, fullWidth: true, maxLength: 400 }),
    f.markdown("body", "Body", { nonNull: true, fullWidth: true }),
    f.media("heroMediaId", "Hero image", ["IMAGE"], { group: "details" }),
    f.relation("authorId", "Author (staff)", "user", "name", { group: "details" }),
    f.text("authorName", "Author name (display)", { group: "details" }),
    f.date("publishedAt", "Display date", { group: "details", hint: "Shown on the article; defaults to the publish date." }),
    f.relation("relatedProgrammeId", "Related programme", "programme", "title", { group: "details" }),
    f.relation("relatedUniversityId", "Related university", "university", "name", { group: "details" }),
    f.stringArray("tagsJson", "Tags", { group: "details", hint: "One per line." }),
    f.select("visibility", "Visibility", VISIBILITY, VISIBILITY_LABELS, { group: "details" }),
    f.date("publishAt", "Publish at", { group: "details", hint: "Set a future date to schedule publication." }),
    ...seo(),
  ],
  publicPaths: (r) => ["/", "/news", `/news/${str(r.slug)}`],
};

export const event: EntityDef = {
  key: "events",
  type: "Event",
  delegate: "event",
  label: "Events",
  labelSingular: "Event",
  description: "Open days, webinars and campus events.",
  titleField: "title",
  searchFields: ["title", "slug", "location"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "startsAt", label: "Starts", kind: "date" },
    { key: "isOnline", label: "Online", kind: "boolean" },
    { key: "status", label: "Status", kind: "status" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["title", "startsAt", "updatedAt"],
  defaultSort: { field: "startsAt", dir: "desc" },
  hasStatus: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the title." }),
    f.date("startsAt", "Starts at", { required: true }),
    f.date("endsAt", "Ends at"),
    f.text("location", "Location"),
    f.boolean("isOnline", "Online event"),
    f.url("registrationUrl", "Registration URL"),
    f.markdown("description", "Description", { nonNull: true, fullWidth: true }),
    f.media("heroMediaId", "Hero image", ["IMAGE"], { group: "details" }),
  ],
  publicPaths: () => ["/news", "/student-life", "/admissions"],
};

export const faq: EntityDef = {
  key: "faqs",
  type: "Faq",
  delegate: "faq",
  label: "FAQs",
  labelSingular: "FAQ",
  description: "Questions grouped by category; optionally attached to a programme.",
  titleField: "question",
  searchFields: ["question", "answer"],
  listColumns: [
    { key: "question", label: "Question" },
    { key: "category", label: "Category", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "sortOrder", label: "Order", kind: "number" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["question", "category", "sortOrder", "updatedAt"],
  defaultSort: { field: "category", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("question", "Question", { required: true, fullWidth: true }),
    f.markdown("answer", "Answer", { required: true, fullWidth: true }),
    f.select("category", "Category", FAQ_CATEGORIES, FAQ_CATEGORY_LABELS),
    f.relation("programmeId", "Programme", "programme", "title"),
    f.number("sortOrder", "Sort order", { integer: true, nonNull: true, min: 0, max: 9999 }),
  ],
  publicPaths: () => ["/faqs", "/admissions", "/programmes"],
};

export const document: EntityDef = {
  key: "documents",
  type: "Document",
  delegate: "document",
  label: "Documents",
  labelSingular: "Document",
  description: "Prospectuses, brochures, policies and forms. Each document links to an uploaded PDF in the media library.",
  titleField: "title",
  searchFields: ["title", "slug", "description"],
  listColumns: [
    { key: "title", label: "Title" },
    { key: "category", label: "Category", kind: "mono" },
    { key: "version", label: "Version", kind: "mono" },
    { key: "visibility", label: "Visibility", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "documentDate", label: "Date", kind: "date" },
  ],
  sortable: ["title", "category", "updatedAt", "documentDate"],
  defaultSort: { field: "category", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("title", "Title", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the title." }),
    f.select("category", "Category", DOCUMENT_CATEGORIES, DOCUMENT_CATEGORY_LABELS),
    f.media("mediaId", "File", ["PDF", "DOCUMENT"], { hint: "Upload the PDF in the media library first." }),
    f.text("version", "Version", { nonNull: true, maxLength: 20 }),
    f.date("documentDate", "Document date"),
    f.select("visibility", "Visibility", VISIBILITY, VISIBILITY_LABELS),
    f.textarea("description", "Description", { fullWidth: true }),
  ],
  publicPaths: () => ["/resources", "/admissions"],
};
