import { FACILITY_CATEGORIES, FACILITY_CATEGORY_LABELS } from "@/lib/enums";
import { CONSENT_LABELS, STORY_CONSENT, f, governance } from "../fields";
import type { EntityDef } from "../types";

const str = (v: unknown) => (typeof v === "string" ? v : "");

export const studentStory: EntityDef = {
  key: "student-stories",
  type: "StudentStory",
  delegate: "studentStory",
  label: "Student stories",
  labelSingular: "Student story",
  description: "Student journeys and quotes. A story cannot be published until consent is recorded as granted.",
  titleField: "studentName",
  searchFields: ["studentName", "slug", "outcome"],
  listColumns: [
    { key: "studentName", label: "Student" },
    { key: "consentStatus", label: "Consent", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["studentName", "updatedAt"],
  defaultSort: { field: "updatedAt", dir: "desc" },
  hasStatus: true,
  fields: [
    f.text("studentName", "Student name", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the name." }),
    f.relation("programmeId", "Programme", "programme", "title"),
    f.relation("pathwayId", "Pathway", "pathway", "title"),
    f.relation("destinationId", "Destination", "destination", "country"),
    f.relation("universityId", "University", "university", "name"),
    f.text("previousEducation", "Previous education"),
    f.markdown("journey", "Journey", { nonNull: true, fullWidth: true }),
    f.textarea("outcome", "Outcome", { group: "details", fullWidth: true }),
    f.textarea("quote", "Quote", { group: "details", fullWidth: true }),
    f.media("photoMediaId", "Photo", ["IMAGE"], { group: "details", hint: "The photo's own consent status must also be granted." }),
    f.url("videoUrl", "Video URL", { group: "details" }),
    f.textarea("progressionEvidence", "Progression evidence", { group: "details", fullWidth: true, hint: "Internal note: how the outcome was verified." }),
    f.boolean("featured", "Featured", { group: "details" }),
    f.select("consentStatus", "Consent status", STORY_CONSENT, CONSENT_LABELS, { group: "governance", hint: "Required: GRANTED before the story can be published." }),
    ...governance({ verification: true }),
  ],
  guardStatus: (record, to) => (to === "PUBLISHED" && record.consentStatus !== "GRANTED" ? "Consent must be granted before a student story can be published." : null),
  guardSave: (values, existing) =>
    existing?.status === "PUBLISHED" && values.consentStatus !== "GRANTED"
      ? "This story is published. Withdraw it (move to Draft or Archived) before changing consent away from granted."
      : null,
  publicPaths: (r) => ["/", "/student-stories", `/student-stories/${str(r.slug)}`],
};

export const faculty: EntityDef = {
  key: "faculty",
  type: "Faculty",
  delegate: "faculty",
  label: "Faculty",
  labelSingular: "Faculty member",
  description: "Leadership and teaching staff profiles shown on the About page.",
  titleField: "name",
  searchFields: ["name", "role", "department", "slug"],
  listColumns: [
    { key: "name", label: "Name" },
    { key: "role", label: "Role" },
    { key: "isLeadership", label: "Leadership", kind: "boolean" },
    { key: "status", label: "Status", kind: "status" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["name", "updatedAt", "sortOrder"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("name", "Name", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the name." }),
    f.text("role", "Role / title", { required: true }),
    f.text("department", "Department"),
    f.markdown("biography", "Biography", { nonNull: true, fullWidth: true }),
    f.textarea("qualifications", "Qualifications", { group: "details", fullWidth: true }),
    f.textarea("expertise", "Expertise", { group: "details", fullWidth: true }),
    f.textarea("achievements", "Achievements", { group: "details", fullWidth: true }),
    f.url("linkedin", "LinkedIn URL", { group: "details" }),
    f.media("photoMediaId", "Photo", ["IMAGE"], { group: "details" }),
    f.boolean("isLeadership", "Leadership team", { group: "details" }),
    f.number("sortOrder", "Sort order", { group: "details", integer: true, nonNull: true, min: 0, max: 9999 }),
  ],
  publicPaths: () => ["/about"],
};

export const facility: EntityDef = {
  key: "facilities",
  type: "Facility",
  delegate: "facility",
  label: "Facilities",
  labelSingular: "Facility",
  description: "Campus spaces shown on the Campus page, grouped by category.",
  titleField: "name",
  searchFields: ["name", "slug"],
  listColumns: [
    { key: "name", label: "Name" },
    { key: "category", label: "Category", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "updatedAt", label: "Updated", kind: "date" },
  ],
  sortable: ["name", "updatedAt", "sortOrder"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("name", "Name", { required: true }),
    f.slug("slug", "Slug", { hint: "Leave blank to generate from the name." }),
    f.select("category", "Category", FACILITY_CATEGORIES, FACILITY_CATEGORY_LABELS),
    f.markdown("description", "Description", { nonNull: true, fullWidth: true }),
    f.media("photoMediaId", "Photo", ["IMAGE"]),
    f.number("sortOrder", "Sort order", { group: "details", integer: true, nonNull: true, min: 0, max: 9999 }),
    ...governance({ verification: true }),
  ],
  publicPaths: () => ["/campus", "/student-life"],
};

export const outcomeMetric: EntityDef = {
  key: "outcome-metrics",
  type: "OutcomeMetric",
  delegate: "outcomeMetric",
  label: "Outcome metrics",
  labelSingular: "Outcome metric",
  description: "Numbers shown in statistics blocks. Unverified or empty values render as 'Verified data pending'.",
  titleField: "label",
  searchFields: ["label", "key"],
  listColumns: [
    { key: "label", label: "Label" },
    { key: "key", label: "Key", kind: "mono" },
    { key: "value", label: "Value", kind: "mono" },
    { key: "status", label: "Status", kind: "status" },
    { key: "verificationStatus", label: "Verification", kind: "verification" },
    { key: "asOfDate", label: "As of", kind: "date" },
  ],
  sortable: ["label", "sortOrder", "updatedAt"],
  defaultSort: { field: "sortOrder", dir: "asc" },
  hasStatus: true,
  fields: [
    f.text("label", "Label", { required: true }),
    f.text("key", "Key", { required: true, maxLength: 60, hint: "Stable identifier used by statistics blocks, e.g. progression_rate." }),
    f.text("value", "Value", { hint: "Leave empty until verified." }),
    f.text("unit", "Unit", { maxLength: 20 }),
    f.date("asOfDate", "As of date"),
    f.number("sortOrder", "Sort order", { integer: true, nonNull: true, min: 0, max: 9999 }),
    ...governance({ verification: true, sourceNote: true }),
  ],
  publicPaths: () => ["/", "/why-st-hughs", "/about"],
};
